var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": "22312", "id_kinopoisk": "972889", "url": "454928-badcomedian-2011", "type": "tv-series", "title": "BadComedian", "title_alternative": null, "tagline": null, "description": "Юмористическое шоу, высмеивающее плохое кино. От российских «шедевров», до американской клюквы. А также серьёзные обзоры и переводы.", "year": 2011, "poster": "\/\/images.kinopoisk.cloud\/posters\/972889.jpg", "trailer": "https:\/\/www.youtube.com\/embed\/vVU8PXzfymg", "age": "зрителям, достигшим 18 лет", "actors": ["Евгений Баженов", "Руслан Габидуллин", "Пётр Иващенко"], "countries": ["Россия"], "genres": ["Комедия"], "directors": ["Евгений Баженов"], "screenwriters": ["Евгений Баженов"], "producers": ["Евгений Баженов"], "operators": null, "composers": null, "painters": null, "editors": ["Евгений Баженов"], "budget": "1руб.", "rating_kinopoisk": "9.207", "rating_imdb": "7.7", "kinopoisk_votes": "27501", "imdb_votes": "27501", "fees_world": null, "fees_russia": null, "premiere_world": null, "premiere_russia": null, "frames": null, "screenshots": ["https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771024.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771025.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771026.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771027.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771028.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771029.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771030.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771031.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771032.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771033.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771034.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771035.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771036.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771037.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/7\/7\/kinopoisk.ru-BadComedian-2771038.jpg"], "seasons": 1, "videocdn": { "url": null, "quality": null, "duration": null, "voice": ["0"], "seasons": null, "episodes": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "collapse": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null } }
        );
    };


