var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": "37100", "id_kinopoisk": "674243", "url": "586175-schastlivye-lyudi-2008", "type": "tv-series", "title": "Счастливые люди", "title_alternative": null, "tagline": null, "description": "Документальный фильм о трудах и днях охотников и их семей из посёлка Бахта в среднем течении реки Енисей в течение целого года.", "year": 2008, "poster": "\/\/images.kinopoisk.cloud\/posters\/674243.jpg", "trailer": "https:\/\/www.youtube.com\/embed\/bITElb4l_SY", "age": null, "actors": null, "countries": ["Россия"], "genres": ["Документальный"], "directors": ["Дмитрий Васюков"], "screenwriters": ["Дмитрий Васюков"], "producers": ["Владимир Перепелкин"], "operators": null, "composers": ["Александр Войтинский"], "painters": null, "editors": null, "budget": null, "rating_kinopoisk": "9.211", "rating_imdb": "8.8", "kinopoisk_votes": "5722", "imdb_votes": "5722", "fees_world": null, "fees_russia": null, "premiere_world": null, "premiere_russia": null, "frames": null, "screenshots": ["https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965265.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965266.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965267.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965268.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965269.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965270.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965271.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965272.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965273.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965274.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965275.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/1\/9\/6\/kinopoisk.ru-Happy-People-1965276.jpg"], "seasons": 1, "videocdn": { "url": null, "quality": null, "duration": null, "voice": ["0"], "seasons": null, "episodes": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "collapse": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null } }
        );
    };


