var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": "35711", "id_kinopoisk": "1007472", "url": "5823-planeta-zemlya-2-2016", "type": "tv-series", "title": "Планета Земля 2", "title_alternative": "Planet Earth II", "tagline": null, "description": "Дэвид Аттенборо демонстрирует невероятные по красоте пейзажи, заповедные и малоизученные уголки Земли.", "year": 2016, "poster": "\/\/images.kinopoisk.cloud\/posters\/1007472.jpg", "trailer": "https:\/\/www.youtube.com\/embed\/c8aFcHFu8QM", "age": null, "actors": ["Дэвид Аттенборо"], "countries": ["Великобритания"], "genres": ["Документальный"], "directors": ["Джастин Андерсон", "Ed Charles", "Фреди Девас"], "screenwriters": null, "producers": ["Ванесса Берловиц", "Джеймс Брикелл", "Джонатан Килинг"], "operators": ["Матео Уиллис", "Джон Шир", "Джонатан Джонс"], "composers": ["Джаша Клебе", "Джейкоб Ши", "Ханс Циммер"], "painters": null, "editors": ["Найджел Бак", "Дэвид Пирс", "Ник Карлине"], "budget": null, "rating_kinopoisk": "9.2", "rating_imdb": "9.5", "kinopoisk_votes": null, "imdb_votes": null, "fees_world": null, "fees_russia": null, "premiere_world": "6 ноября 2016", "premiere_russia": null, "frames": ["https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338390.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338391.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338392.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338393.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338394.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338395.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338396.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338397.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338398.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338399.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338400.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338401.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/3\/3\/kinopoisk.ru-Planet-Earth-II-3338402.jpg"], "screenshots": null, "seasons": 1, "videocdn": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null }, "collapse": { "url": ["\/embed\/movie\/3583"], "quality": ["HD (720p)"], "duration": null, "voice": ["Jimmy J", "Рус. Люб. двухголосый", "Укр. Одноголосий", "Eng.Original"], "seasons": null, "episodes": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null, "seasons": null, "episodes": null } }
        );
    };


