var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": 368539, "id_kinopoisk": 1003587, "url": "27832-gamilton-2015", "type": "movie", "title": "Гамильтон", "title_alternative": "Hamilton", "tagline": null, "description": "Перед нами 'Гамильтон' — открытие в жанре мюзикла. Это рассказ об одном из отцов-основателей, написанный хип-хопом в сочетании с классическим Бродвеем, который заставит вас плакать", "year": 2015, "poster": "\/\/images.kinopoisk.cloud\/posters\/1003587.jpg", "trailer": "https:\/\/www.youtube.com\/embed\/5snjgB9PO48", "age": null, "actors": ["Лин-Мануэль Миранда", "Лесли Одом мл.", "Давид Диггс", "Филлипа Су", "Рене Голдсберри", "Окьерете Онаодован", "Энтони Рамос", "Джонатан Грофф", "Кристофер Нил Джексон", "Жасмин Сепас Джонс"], "countries": ["США"], "genres": ["Мюзикл"], "directors": ["Томас Каил"], "screenwriters": ["Лин-Мануэль Миранда", "Ron Chernow"], "producers": ["Джилл Фурман", "Sander Jacobs", "Лин-Мануэль Миранда"], "operators": null, "composers": ["Alex Lacamoire"], "painters": ["Пол Тэйзуэлл"], "editors": null, "budget": null, "rating_kinopoisk": 9.261, "rating_imdb": null, "kinopoisk_votes": "510", "imdb_votes": "510", "fees_world": null, "fees_russia": null, "premiere_world": "6 августа 2015", "premiere_russia": null, "frames": ["https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825620.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825621.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825622.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825623.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825624.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2825625.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826010.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826011.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826012.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826013.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826014.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826015.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826016.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826017.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/2\/kinopoisk.ru-Hamilton-2826018.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/8\/3\/kinopoisk.ru-Hamilton-2835192.jpg"], "screenshots": null, "videocdn": { "url": null, "quality": null, "duration": null, "voice": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null }, "collapse": { "url": null, "quality": null, "duration": null, "voice": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null } }
        );
    };


