var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": 39843, "id_kinopoisk": 45319, "url": "408479-zhil-byl-pes-1982", "type": "movie", "title": "Жил-был пёс", "title_alternative": null, "tagline": null, "description": "Жил-был пёс. Верно служил, но выгнали его по старости. И решил он повеситься, да повстречал в лесу такого же старого волка", "year": 1982, "poster": "images.kinopoisk.cloud\/posters\/45319.jpg", "trailer": "https:\/\/www.youtube.com\/embed\/twSn58BPgWM", "age": "зрителям, достигшим 6 лет", "actors": ["Георгий Бурков", "Армен Джигарханян", "Эдуард Назаров"], "countries": ["СССР"], "genres": ["Мультфильм", "Короткометражка", "Комедия", "Семейный"], "directors": ["Эдуард Назаров"], "screenwriters": ["Эдуард Назаров"], "producers": null, "operators": ["Михаил Друян"], "composers": null, "painters": ["Алла Горева", "Эдуард Назаров"], "editors": null, "budget": null, "rating_kinopoisk": 9.196, "rating_imdb": 8.6, "kinopoisk_votes": "75750", "imdb_votes": "75750", "fees_world": null, "fees_russia": null, "premiere_world": "12 июля 2016", "premiere_russia": null, "frames": ["https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361251.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361252.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361253.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361254.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361255.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361256.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/3\/6\/1\/kinopoisk.ru-Zhil-byl-pyos-361257.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/6\/9\/kinopoisk.ru-Zhil-byl-pyos-2698822.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/6\/9\/kinopoisk.ru-Zhil-byl-pyos-2698823.jpg"], "screenshots": null, "videocdn": { "url": null, "quality": null, "duration": null, "voice": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null }, "collapse": { "url": null, "quality": null, "duration": null, "voice": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null } }
        );
    };


