var task = require('../model/model_task');

module.exports =
    function (req, res) {
        res.send(
            { "id": 491312, "id_kinopoisk": 798117, "url": "311570-dvenadcataya-noch-2012", "type": "movie", "title": "Двенадцатая ночь", "title_alternative": "Twelfth Night", "tagline": null, "description": "«Двенадцатая ночь»  комедия запутанных романтических отношений, искрящаяся наиболее изящными диалогами, когда-либо написанными Уильямом Шекспиром.", "year": 2012, "poster": "\/\/images.kinopoisk.cloud\/posters\/798117.jpg", "trailer": null, "age": "зрителям, достигшим 16 лет", "actors": ["Стивен Фрай", "Марк Райлэнс", "Сэмюэл Барнетт", "Лайам Бреннан", "Пол Чахиди", "Джон Пол Коннолли", "Джонни Флинн", "Джеймс Гарнон", "Питер Хэмилтон Дайер", "Колин Хёрли"], "countries": ["Великобритания"], "genres": ["Комедия"], "directors": ["Тим Кэрролл"], "screenwriters": ["Уильям Шекспир"], "producers": ["Джеймс Уитбурн"], "operators": null, "composers": ["Клер ван Кампен"], "painters": ["Дженни Тирамани"], "editors": null, "budget": null, "rating_kinopoisk": 8.808, "rating_imdb": 8.8, "kinopoisk_votes": "1379", "imdb_votes": "1379", "fees_world": null, "fees_russia": null, "premiere_world": "22 июня 2013", "premiere_russia": "12 ноября 2014", "frames": ["https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254678.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254679.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254681.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254682.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254683.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254684.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254685.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2254686.jpg"], "screenshots": ["https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2251496.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2251497.jpg", "https:\/\/st.kp.yandex.net\/im\/kadr\/2\/2\/5\/kinopoisk.ru-Twelfth-Night-2251498.jpg"], "videocdn": { "url": null, "quality": null, "duration": null, "voice": null }, "hdvb": { "url": null, "quality": null, "duration": null, "voice": null }, "collapse": { "url": null, "quality": null, "duration": null, "voice": null }, "kodik": { "url": null, "quality": null, "duration": null, "voice": null } }
        );
    };


